<a href="https://colab.research.google.com/github/muhamadrefo/ImageClassificationColab/blob/master/SVM6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
#Importing Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix as cm
from sklearn import model_selection
from sklearn.model_selection import train_test_split as tt, GridSearchCV
from sklearn.metrics import classification_report
%matplotlib inline

In [3]:
%cd /content/drive/My Drive/TestingPlace/PlaceofDatabase/CNN/

/content/drive/My Drive/TestingPlace/PlaceofDatabase/CNN


In [4]:
#Read Dataset
dataTrain = pd.read_csv('DataTraining.csv')
dataValid = pd.read_csv('DataValidation.csv')

In [12]:
X = dataTrain.iloc[:, 1:6].values
Y = dataTrain.iloc[:, 7].values
X_train, X_test, y_train, y_test = tt(X,y, test_size= 0.2, random_state=3)

#SVM Linear
def Linear():
  model = SVC(kernel='linear', C=100.0 , gamma=10)
  return model

#SVM Gaussian 
def RBF():
  model = SVC(kernel='rbf', C=100.0 , gamma=10)
  return model

#SVM Polynomial
def Poly():
  model = SVC(kernel='poly', degree=8, C=100.0 , gamma=10)
  return model

#SVM Sigmoid
def Sigmoid():
  model = SVC(kernel='sigmoid', C=100.0 , gamma=10)
  return model

def runLin():
  model = Linear()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print('Accuracy Score: ', accuracy_score(y_test, y_pred)*100)
  print('Confussion matrix: \n', cm(y_test, y_pred))
  print('Classification report: \n', classification_report(y_test, y_pred))

def runSig():
  model = Sigmoid()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print('Accuracy Score: ', accuracy_score(y_test, y_pred)*100)
  print('Confussion matrix: \n', cm(y_test, y_pred))
  print('Classification report: \n', classification_report(y_test, y_pred))

def runGauss():
  model = RBF()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print('Accuracy Score: ', accuracy_score(y_test, y_pred)*100)
  print('Confussion matrix: \n', cm(y_test, y_pred))
  print('Classification report: \n', classification_report(y_test, y_pred))

def runPoly():
  model = Poly()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print('Accuracy Score: ', accuracy_score(y_test, y_pred)*100)
  print('Confussion matrix: \n', cm(y_test, y_pred))
  print('Classification report: \n', classification_report(y_test, y_pred))

In [13]:
runLin()

Accuracy Score:  75.29411764705883
Confussion matrix: 
 [[27 16]
 [ 5 37]]
Classification report: 
               precision    recall  f1-score   support

         cap       0.84      0.63      0.72        43
       tulis       0.70      0.88      0.78        42

    accuracy                           0.75        85
   macro avg       0.77      0.75      0.75        85
weighted avg       0.77      0.75      0.75        85



In [14]:
runSig()

Accuracy Score:  50.588235294117645
Confussion matrix: 
 [[43  0]
 [42  0]]
Classification report: 
               precision    recall  f1-score   support

         cap       0.51      1.00      0.67        43
       tulis       0.00      0.00      0.00        42

    accuracy                           0.51        85
   macro avg       0.25      0.50      0.34        85
weighted avg       0.26      0.51      0.34        85



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
runPoly()

Accuracy Score:  89.41176470588236
Confussion matrix: 
 [[36  7]
 [ 2 40]]
Classification report: 
               precision    recall  f1-score   support

         cap       0.95      0.84      0.89        43
       tulis       0.85      0.95      0.90        42

    accuracy                           0.89        85
   macro avg       0.90      0.89      0.89        85
weighted avg       0.90      0.89      0.89        85



In [16]:
runGauss()

Accuracy Score:  90.58823529411765
Confussion matrix: 
 [[36  7]
 [ 1 41]]
Classification report: 
               precision    recall  f1-score   support

         cap       0.97      0.84      0.90        43
       tulis       0.85      0.98      0.91        42

    accuracy                           0.91        85
   macro avg       0.91      0.91      0.91        85
weighted avg       0.91      0.91      0.91        85

