<a href="https://colab.research.google.com/github/muhamadrefo/ImageClassificationColab/blob/master/SVMClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prepare Environment

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [21]:
#Importing Packages

import numpy as np
import matplotlib.pyplot as plt
import csv
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix as cm
from sklearn import model_selection
from sklearn.model_selection import train_test_split as tt
from sklearn.metrics import classification_report

In [3]:
%cd /content/drive/My Drive/Batik/

/content/drive/My Drive/Batik


# Reading the Dataset

In [33]:
import pandas as pd
#data = pd.read_csv('DataValidation.csv')
data = pd.read_csv('DataTraining.csv')

#Encoding the Categorical Data

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = data.apply(le.fit_transform)
df.head(15)

Path  Dissimilarity  Contrast  Homogeneity  Energy  Correlation  ASM  Label
0    202            402       383          117     172           40  172      0
1     17            529       519            2      11          213   11      0
2    204            322       273          188     198          118  198      0
3    189            380       339          136     180           75  180      0
4    223            296       295          239     337          121  337      0
5    200            362       328          154     177           82  177      0
6    261            390       399          159      60          394   60      0
7     23            215       206          315     449           92  449      0
8    227            488       489           44      44          241   44      0
9    270            530       528            4      17          183   17      0
10   276            511       513           22       3          227    3      0
11     1            360       381          176     336          102  336      0
12   255            344       377          199      87          417   87      0
13     0            157       167          379     446          197  446      0
14   230            525       526            8      25          140   25      0

#Splitting the Data into Training and Testing Data

In [36]:
X = df.iloc[:, 1:6].values
Y = df.iloc[:, 7].values
X_train, X_test, Y_train, Y_test = tt(X,Y, test_size=0.2, random_state=4)

In [37]:
X_train

array([[145, 190, 400, 330, 512],
       [130, 138, 407, 473, 127],
       [ 98, 113, 436, 496, 194],
       ...,
       [213, 175, 307, 289, 215],
       [445, 460,  95, 246,  33],
       [520, 507,   6,  23, 193]])

In [38]:
X_train.shape

(428, 5)

#Model SVM Start Here

**Polynomial**

In [39]:
# Kernel Polynomial
modelSVM = svm.SVC(C=1.0, kernel='poly', gamma='scale', probability=True)
modelSVM.fit(X_train, Y_train)
y_pred = modelSVM.predict(X_test)

In [40]:
print("histogram y_pred\n",np.histogram(y_pred))
print("histogram Y_test\n",np.histogram(Y_test))
print("Confusion Matriks\n", cm(Y_test, modelSVM.predict(X_test)))

histogram y_pred
 (array([48,  0,  0,  0,  0,  0,  0,  0,  0, 60]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
histofram Y_test
 (array([55,  0,  0,  0,  0,  0,  0,  0,  0, 53]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
Confusion Matriks
 [[46  9]
 [ 2 51]]


In [41]:
print("Classification Report:\n", classification_report(Y_test,y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.84      0.89        55
           1       0.85      0.96      0.90        53

    accuracy                           0.90       108
   macro avg       0.90      0.90      0.90       108
weighted avg       0.91      0.90      0.90       108



In [42]:
print("Accuracy Score: ", accuracy_score(np.delete(Y_test, np.where(np.isnan(X_test).any(axis=1))), y_pred))

Accuracy Score:  0.8981481481481481


**RBF**

In [43]:
modelSVM = svm.SVC(C=1.0, kernel='rbf', gamma='scale', probability=True)
modelSVM.fit(X_train, Y_train)
y_pred = modelSVM.predict(X_test)

print("histogram y_pred\n",np.histogram(y_pred))
print("histogram Y_test\n",np.histogram(Y_test))
print("Confusion Matriks\n", cm(Y_test, modelSVM.predict(X_test)))

histogram y_pred
 (array([44,  0,  0,  0,  0,  0,  0,  0,  0, 64]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
histofram Y_test
 (array([55,  0,  0,  0,  0,  0,  0,  0,  0, 53]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
Confusion Matriks
 [[42 13]
 [ 2 51]]


In [44]:
print("Classification Report:\n", classification_report(Y_test,y_pred))
print("Accuracy Score: ", accuracy_score(np.delete(Y_test, np.where(np.isnan(X_test).any(axis=1))), y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.76      0.85        55
           1       0.80      0.96      0.87        53

    accuracy                           0.86       108
   macro avg       0.88      0.86      0.86       108
weighted avg       0.88      0.86      0.86       108

Accuracy Score:  0.8611111111111112


**SIGMOID**

In [45]:
modelSVM = svm.SVC(C=1.0, kernel='sigmoid', gamma='scale', probability=True)
modelSVM.fit(X_train, Y_train)
y_pred = modelSVM.predict(X_test)

print("histogram y_pred\n",np.histogram(y_pred))
print("histogram Y_test\n",np.histogram(Y_test))
print("Confusion Matriks\n", cm(Y_test, modelSVM.predict(X_test)))

histogram y_pred
 (array([64,  0,  0,  0,  0,  0,  0,  0,  0, 44]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
histogram Y_test
 (array([55,  0,  0,  0,  0,  0,  0,  0,  0, 53]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
Confusion Matriks
 [[22 33]
 [42 11]]


In [46]:
print("Classification Report:\n", classification_report(Y_test,y_pred))
print("Accuracy Score: ", accuracy_score(np.delete(Y_test, np.where(np.isnan(X_test).any(axis=1))), y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.34      0.40      0.37        55
           1       0.25      0.21      0.23        53

    accuracy                           0.31       108
   macro avg       0.30      0.30      0.30       108
weighted avg       0.30      0.31      0.30       108

Accuracy Score:  0.3055555555555556


**LINEAR**

In [47]:
modelSVM = svm.SVC(C=1.0, kernel='linear', gamma='scale', probability=True)
modelSVM.fit(X_train, Y_train)
y_pred = modelSVM.predict(X_test)

print("histogram y_pred\n",np.histogram(y_pred))
print("histogram Y_test\n",np.histogram(Y_test))
print("Confusion Matriks\n", cm(Y_test, modelSVM.predict(X_test)))

histogram y_pred
 (array([55,  0,  0,  0,  0,  0,  0,  0,  0, 53]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
histogram Y_test
 (array([55,  0,  0,  0,  0,  0,  0,  0,  0, 53]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))
Confusion Matriks
 [[35 20]
 [20 33]]


In [48]:
print("Classification Report:\n", classification_report(Y_test,y_pred))
print("Accuracy Score: ", accuracy_score(np.delete(Y_test, np.where(np.isnan(X_test).any(axis=1))), y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.64      0.64        55
           1       0.62      0.62      0.62        53

    accuracy                           0.63       108
   macro avg       0.63      0.63      0.63       108
weighted avg       0.63      0.63      0.63       108

Accuracy Score:  0.6296296296296297
